### PR TITLE
Restrict Enum34 dependency to python 3.4 or less.

### LINKED ISSUE #17: Restrict enum34 dependency to python < 3.4
Hi folks,

I recently migrated a python project from 3.4 to 3.6 and bumped into an issue caused by a dependency on enum34.

Having a dig around, that dependency is drawn from invocations itself, but is caused because the backport doesn't include features that the 3.6 enum stdlib does include.

Can we consider pinning the enum34 dependency to python <3.4?

### PR DESCRIPTION
**Pull request by ABitMoreDepth**
Resolves #17

### CODE REVIEW

**Comment by ABitMoreDepth** [comment]
It looks like one of the tests is failing due to an error with PyYaml (I hit this at work recently as well), restricting pyyaml to version 5.2 (the last version to support 3.4) may perhaps fix?

**Comment by ABitMoreDepth** [comment]
Ping @bitprophet is there any chance we could land this PR in the near future?  Apologies for the spam.

**Comment by ABitMoreDepth** [comment]
I don't think I have permission to merge this, could someone who does please do so?

**Comment by bitprophet** [comment]
Merged #21 instead, apologies!

**Comment by utapyngo** [comment]
@bitprophet is there any reason why #21 has been merged instead of this PR? The changes are not identical.

**Comment by bitprophet** [comment]
See https://github.com/pyinvoke/invocations/issues/17#issuecomment-768393501

**Comment by ABitMoreDepth** [comment]
Change makes sense, thanks. :)

**Pull request closed without merging**
